# Generated by Django 5.0.7 on 2025-02-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('reward', models.FloatField()),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('transaction_hash', models.CharField(max_length=256)),
                ('contractee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractee', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor', to=settings.AUTH_USER_MODEL)),
                ('mediator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
