# Generated by Django 5.0.7 on 2025-02-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contract_contractee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='transaction_hash',
        ),
    ]
