# Generated by Django 5.0.7 on 2025-02-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_contract_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='proof',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
