# Generated by Django 5.0.7 on 2025-02-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
